import './globals.css'
import { Roboto_Flex } from "next/font/google"

import Header from '@/components/Header'
import Provider from '@/components/Provider'

const roboto = Roboto_Flex({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Provider>
          {/* Header  */}
          <Header />

          {children}
        </Provider>

      </body>
    </html>
  )
}
